export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const USERS_STATE_CHANGE = "USERS_STATE_CHANGE";
export const USER_POSTS_STATE_CHANGE = "USER_POSTS_STATE_CHANGE";
export const USER_FOLLOWING_LIST_CHANGE = "USER_FOLLOWING_LIST_CHANGE";
export const USER_FOLLOWING_POSTS_CHANGE = "USER_FOLLOWING_POSTS_CHANGE";
